### ISSUE TITLE
Getting an IOException when runned

### ISSUE THREAD

**Issue by Seniru** [salifm/projstats#1]
Hello! When I run  this program I get this error.
`java.io.IOException: Cannot run program "file": CreateProcess error=2, The System cannot find the file specified
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:589)
	at java.base/java.lang.Runtime.exec(Runtime.java:448)
	at com.salifm.projstats.Walker.walkIntoFile(Walker.java:63)
	at com.salifm.projstats.Walker.walk(Walker.java:52)
	at com.salifm.projstats.Walker.<init>(Walker.java:33)
	at com.salifm.projstats.Main.main(Main.java:48)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:420)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:151)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 7 more
java.io.IOException: Cannot run program "file": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:589)
	at java.base/java.lang.Runtime.exec(Runtime.java:448)
	at com.salifm.projstats.Walker.walkIntoFile(Walker.java:63)
	at com.salifm.projstats.Walker.walk(Walker.java:52)
	at com.salifm.projstats.Walker.walk(Walker.java:45)
	at com.salifm.projstats.Walker.walk(Walker.java:45)
	at com.salifm.projstats.Walker.<init>(Walker.java:33)
	at com.salifm.projstats.Main.main(Main.java:48)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:420)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:151)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 9 more
`
This keeps repeating.

*And finally it outputs this in the terminal*

directory:C:\Users\******\Documents\NetBeansProjects
name: NetBeansProjects
size: 0.00 B / 0.00 B
files: 0
folders: 17
lines: 0
empty lines: 0
extensions:

**System Information**
- OS: Windows 10
- Java version: 12
- I used both terminal and netbeans and got the same error. For terminal I used the command `-java -cp dist\Projstats.jar com.salifm.projstats.Main --cli --list-skipped --skip-dir=META-INF` to run the program

**Comment by Seniru** [comment]
I think this error occurs because  there is no command like `file` in windows. Therefore you'll need to figure out another way to do it. 😕
